version: '3.8'

services:
  jarvis-server:
    build: .
    container_name: jarvis-server
    ports:
      - "8080:8080"
    environment:
      - JARVIS_SERVER_PORT=8080
      - JARVIS_STT_PROVIDER=mock
      - JARVIS_TTS_PROVIDER=mock
      - JARVIS_LLM_PROVIDER=ollama
      - JARVIS_OLLAMA_URL=http://localhost:11434
      - JARVIS_OLLAMA_MODEL=gemma3:1b
      # Add real API Keys here when providers are implemented
      #Gemini:
      - JARVIS_OPENAI_KEY=AIzaSyBLTkS4wzBef3DR72ktUp5NKryE4JlVGDwsk
      - jarvis.gemini.url=https://generativelanguage.googleapis.com
      - jarvis.gemini.key=AIzaSyBLTkS4wzBef3DR72ktUp5NKryE4JlVGDwsk
      - jarvis.gemini.model=gemini-2.5-flash
    #  restart: unless-stopped
    #  depends_on:
    #    - ollama
    #ollama:
    #  image: ollama/ollama:latest
    #  container_name: jarvis-ollama
    #  ports:
    #   - "11434:11434"
    # volumes:
    #  - ollama_data:/root/.ollama
    #restart: unless-stopped

    #volumes:
    # ollama_data:
